blank_issues_enabled: true
contact_links:
  - name: 유니콘 프로 애드블록을 사용하시나요?
    url: https://support.getunicorn.app/hc/ko/community/topics
    about: 유니콘 공식 지원 페이지을 통해 t.hi098123.com 웹 사이트에 있는 안티-애드블록 스크립트를 차단해라고 요청하게끔 리다이렉트합니다.