name: 안티-애드블록
description: 웹 사이트에서 유저스크립트나 애드블록이 감지되었다고 하는 문제를 제보합니다.
title: "anti-adblock: "
labels: ["anti-adblock"]
body:

  - type: textarea
    id: issue_url
    attributes:
      label: "URL"
      description: "같은 문제를 가지는 URL를 적어주세요. 파일은 첨부하지 마세요."
    validations:
      required: true
  
  - type: textarea
    id: filters
    attributes:
      label: "필터"
      description: "구독하신 필터들을 적어주세요. 재구현하는 데 중요합니다."
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: "브라우저"
      description: "어느 브라우저에서 문제가 발생하나요?"
      multiple: true
      options:
        - Mozilla Firefox
        - Google Chrome
        - Microsoft Edge
        - Naver Whale
        - Apple Safari
        - Samsung Internet
        - Opera
        - Vivaldi
        - Brave
        - (Other)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "운영체제"
      description: "어느 운영체계를 사용하시고 계신가요?"
      multiple: true
      options:
        - Microsoft Windows 11
        - Microsoft Windows 10
        - Ubuntu
        - Kubuntu
        - openSUSE
        - HamoniKR
        - Gooroom OS
        - Pop!_OS
        - Red Hat Linux
        - Fedora
        - Manjaro Linux
        - Arch Linux
        - Chromium OS (Chrome OS and WhaleOS도 포함됨.)
        - Qubes OS
        - Android
        - Apple macOS
        - Apple iOS
        - (Other)
    validations:
      required: true
      
  - type: dropdown
    id: adblocker
    attributes:
      label: "애드블록"
      description: "어떤 애드블록을 사용하신가요?"
      multiple: true
      options:
        - AdGuard Browser Extension
        - AdGuard for Windows
        - AdGuard for Android
        - AdGuard for iOS/iOS Pro
        - AdGuard for Mac
        - AdGuard for Safari
        - AdGuard Content Blocker
        - AdGuard DNS
        - uBlock Origin
        - (Other)
    validations:
      required: true

  - type: dropdown
    id: userscriptmgr
    attributes:
      label: "유저스크립트 매니저"
      description: "hi098123-tool-cracker 유저스크립트를 어느 유저스크립트 매니저에 설치하셨나요?"
      multiple: true
      options:
        - Tampermonkey
        - Greasemonkey
        - Violentmonkey
        - AdGuard for Windows
        - AdGuard for macOS
        - AdGuard for Android
        - quoid/userscripts
        - (Other)
    validations:
      required: true

  - type: textarea
    id: userscript
    attributes:
      label: "유저스크립트"
      description: "설치하신 유저스크립트를 모두 적어주세요. 재구현하는 데 중요합니다."
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: "코멘트"
    validations:
      required: false